port: "8080"
database:
  host: "db:3306"
  database: "cakestore"
  username: "cakeuser"
  password: "test"
  maxIdleConns: 5
  maxOpenConns: 20
  connMaxLifeTime: "1h"
  connMaxIdleTime: "15m"
redis:
  host: "redis:6379"
  exp: "5m"
