port: "8080"
database:
  host: "localhost:3306"
  database: "cakestore"
  username: "user"
  password: "password"
  maxIdleConns: 5
  maxOpenConns: 20
  connMaxLifeTime: "1h"
  connMaxIdleTime: "15m"
