version: "3.8"

services:
  cake-app:
    image: cake:1.0
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - db
      - redis

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "cakestore"
      MYSQL_USER: "cakeuser"
      MYSQL_PASSWORD: "test"
      MYSQL_ROOT_PASSWORD: "test"
    ports:
      - "3306:3306"
    volumes:
      - my-db-new:/var/lib/mysql

  redis:
    image: redis:5.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - "redis_db:/data"
volumes:
  my-db-new:
  redis_db:
