version: "3.8"

services:
  cake-store-go-service-1:
    image: cake-store:1.0
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    container_name: godockerDB
    environment:
      MYSQL_DATABASE: "cakestore"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
