// Code generated by MockGen. DO NOT EDIT.
// Source: cake-store/src/model (interfaces: CakeService)

// Package mock is a generated GoMock package.
package mock

import (
	model "cake-store/src/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCakeService is a mock of CakeService interface.
type MockCakeService struct {
	ctrl     *gomock.Controller
	recorder *MockCakeServiceMockRecorder
}

// MockCakeServiceMockRecorder is the mock recorder for MockCakeService.
type MockCakeServiceMockRecorder struct {
	mock *MockCakeService
}

// NewMockCakeService creates a new mock instance.
func NewMockCakeService(ctrl *gomock.Controller) *MockCakeService {
	mock := &MockCakeService{ctrl: ctrl}
	mock.recorder = &MockCakeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCakeService) EXPECT() *MockCakeServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCakeService) Create(arg0 context.Context, arg1 model.CreateUpdateRequest) (*model.Cake, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*model.Cake)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCakeServiceMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCakeService)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockCakeService) Delete(arg0 context.Context, arg1 int) (*model.Cake, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(*model.Cake)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockCakeServiceMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCakeService)(nil).Delete), arg0, arg1)
}

// FindAll mocks base method.
func (m *MockCakeService) FindAll(arg0 context.Context) ([]*model.Cake, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", arg0)
	ret0, _ := ret[0].([]*model.Cake)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockCakeServiceMockRecorder) FindAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockCakeService)(nil).FindAll), arg0)
}

// FindById mocks base method.
func (m *MockCakeService) FindById(arg0 context.Context, arg1 int) (*model.Cake, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", arg0, arg1)
	ret0, _ := ret[0].(*model.Cake)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockCakeServiceMockRecorder) FindById(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockCakeService)(nil).FindById), arg0, arg1)
}

// Update mocks base method.
func (m *MockCakeService) Update(arg0 context.Context, arg1 model.CreateUpdateRequest, arg2 int) (*model.Cake, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(*model.Cake)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCakeServiceMockRecorder) Update(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCakeService)(nil).Update), arg0, arg1, arg2)
}
